<a href="https://colab.research.google.com/github/Vashi1/Computer_Vision_assignments/blob/main/21218_Rakshith_Assesment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays

In [4]:
import numpy as np

In [59]:
import array
import random
x = random.sample(range(0, 29), 10)
a1 = array.array('b', x)
print(a1)
print("Traversal")
for a in a1:
  print(a, end = " ")
print()
print("Insertion: ")
a1.insert(1, 98)
print(a1)
print("Deletion")
a1.pop(1)
print(a1)
print("Search")
ele = int(input("Enter element to be searched: "))
for i in range(len(a1)):
  if a1[i] == ele:
    print(i)
    break
else:
  print("Element not found")
print("Updation")
a1[3] = 87
print(a1)
print()

a2 = array.array("B", x)
print(a2)
print("Traversal")
for a in a2:
  print(a, end = " ")
print()
print("Insertion: ")
a1.insert(1, 8)
print(a2)
print("Deletion")
a1.pop(1)
print(a2)
print("Search")
ele = int(input("Enter element to be searched: "))
for i in range(len(a2)):
  if a2[i] == ele:
    print(i)
    break
else:
  print("Element not found")
print("Updation")
a2[3] = 84
print(a2)
print()

a3 = array.array('f', x)
print(a3)
print("Traversal")
for a in a3:
  print(a, end = " ")
print()
print("Insertion: ")
a1.insert(1, 98)
print(a3)
print("Deletion")
a1.pop(1)
print(a3)
print("Search")
ele = int(input("Enter element to be searched: "))
for i in range(len(a3)):
  if a3[i] == ele:
    print(i)
    break
else:
  print("Element not found")
print("Updation")
a3[3] = 87
print(a3)
print()

a4 = array.array('d', x)
print(a4)
print("Traversal")
for a in a4:
  print(a, end = " ")
print()
print("Insertion: ")
a1.insert(1, 98)
print(a4)
print("Deletion")
a1.pop(1)
print(a4)
print("Search")
ele = int(input("Enter element to be searched: "))
for i in range(len(a4)):
  if a4[i] == ele:
    print(i)
    break
else:
  print("Element not found")
print("Updation")
a4[3] = 87
print(a4)
print()

array('b', [24, 2, 13, 3, 19, 1, 18, 8, 20, 15])
Traversal
24 2 13 3 19 1 18 8 20 15 
Insertion: 
array('b', [24, 98, 2, 13, 3, 19, 1, 18, 8, 20, 15])
Deletion
array('b', [24, 2, 13, 3, 19, 1, 18, 8, 20, 15])
Search
Enter element to be searched: 321
Element not found
Updation
array('b', [24, 2, 13, 87, 19, 1, 18, 8, 20, 15])

array('B', [24, 2, 13, 3, 19, 1, 18, 8, 20, 15])
Traversal
24 2 13 3 19 1 18 8 20 15 
Insertion: 
array('B', [24, 2, 13, 3, 19, 1, 18, 8, 20, 15])
Deletion
array('B', [24, 2, 13, 3, 19, 1, 18, 8, 20, 15])
Search
Enter element to be searched: 24
0
Updation
array('B', [24, 2, 13, 84, 19, 1, 18, 8, 20, 15])

array('f', [24.0, 2.0, 13.0, 3.0, 19.0, 1.0, 18.0, 8.0, 20.0, 15.0])
Traversal
24.0 2.0 13.0 3.0 19.0 1.0 18.0 8.0 20.0 15.0 
Insertion: 
array('f', [24.0, 2.0, 13.0, 3.0, 19.0, 1.0, 18.0, 8.0, 20.0, 15.0])
Deletion
array('f', [24.0, 2.0, 13.0, 3.0, 19.0, 1.0, 18.0, 8.0, 20.0, 15.0])
Search
Enter element to be searched: 13
2
Updation
array('f', [24.0, 2.0, 13.0, 

# Numpy

*Q1*

In [11]:
dob = np.array([2003, 8, 5])
print(dob)
print("Year: ", dob[0])
dob[0] = 2023
print(dob)

a1 = np.array(range(567, 890, 3))
print(a1)
print("8th Number", a1[7])
print("15th Number", a1[14])


[2003    8    5]
Year:  2003
[2023    8    5]
[567 570 573 576 579 582 585 588 591 594 597 600 603 606 609 612 615 618
 621 624 627 630 633 636 639 642 645 648 651 654 657 660 663 666 669 672
 675 678 681 684 687 690 693 696 699 702 705 708 711 714 717 720 723 726
 729 732 735 738 741 744 747 750 753 756 759 762 765 768 771 774 777 780
 783 786 789 792 795 798 801 804 807 810 813 816 819 822 825 828 831 834
 837 840 843 846 849 852 855 858 861 864 867 870 873 876 879 882 885 888]
8th Number 588
15th Number 609


In [82]:
ra = np.random.randint(0, 100, (10, ))
print(ra)
print("Mean", ra.mean())
print("Standard Deviation", ra.std())

rb = np.random.randint(0, 100, (10,))
print(rb)
rc = np.zeros((10, ))
print(rc)
for i in range(len(rc)):
  rc[i] = (ra[i] + rb[i]) /2
print("After Averaging")
print(rc)
print(rc.mean())
rd = np.random.randint(0, 100, (10, )).astype(float)
print(rd)
print("Mean: ", rd.mean())
#Mean would be approximately zero because of central limit theorem
print("Standard Deviation: ", rd.std())
print("Max", max(rd), ", Min", min(rd))


[50 46  9 76 62 15 11 12 33 92]
Mean 40.6
Standard Deviation 28.064924728208343
[46 51 34 89 38 13 13 77 75 26]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After Averaging
[48.  48.5 21.5 82.5 50.  14.  12.  44.5 54.  59. ]
43.4
[41. 63. 12.  6. 91. 50. 66.  6. 79. 79.]
Mean:  49.3
Standard Deviation:  30.29867983922732
Max 91.0 , Min 6.0


In [103]:
arr = np.random.randint(0, 100, (20, ))
print(arr)
print("Max", max(arr))
l = []
for i in arr:
  if i % 2 != 0:
    l.append(i)
print(l)
l1 = []
l1.append(l[0])
l1.append(l[-1])
print(l1)

arr1 = np.random.randint(0, 1000, (20, )).astype(float)
print(arr1)
print("mean", arr1.mean())
arr2 = arr1[arr1 < arr1.mean()]
print(arr2)
arr3 = arr1[arr1 < arr.mean() - arr.std()]
print(arr3)

[19 57 30 72  9 32 66 49 14 14 11 93  7 96 13 56 98 19 21 36]
Max 98
[19, 57, 9, 49, 11, 93, 7, 13, 19, 21]
[19, 21]
[187. 745. 914. 452. 499. 443. 125. 425. 222. 202. 450. 475. 384. 741.
 191.  61. 119. 374. 342. 170.]
mean 376.05
[187. 125. 222. 202. 191.  61. 119. 374. 342. 170.]
[]


In [97]:
arr = np.random.randint(0, 100, (10, ))
print(arr)
print(arr.mean())
for i in range(len(arr)):
  if (arr[i] > arr.mean() + arr.std()) or (arr[i] < arr.mean() - arr.std()):
    arr[i] = arr.mean()
print(arr)

arr1 = np.random.randint(0, 100, (20, )).astype(float)
print(arr1)
print("Mean", arr1.mean())
print("Standard Deviation", arr1.std())
for i in range(len(arr1)):
  if (int(arr1[i]) > arr1.mean() + arr1.std()) or (int(arr1[i]) < arr1.mean() - arr1.std()):
    arr1[i] = arr1.mean()
print(arr1)


[64 35 96 64 95 36 97 52 23 59]
62.1
[64 62 64 64 61 58 60 52 56 59]
[17. 25. 98. 12. 87. 17. 82. 84. 17. 18. 89. 36. 69. 51. 72.  9. 97. 68.
 81. 36.]
Mean 53.25
Standard Deviation 31.57194165711067
[53.25       25.         55.0625     52.915625   54.96140625 53.35947656
 55.17745039 53.83632291 52.32813906 54.09454601 55.89927331 36.
 69.         51.         72.         54.24423697 56.50644882 54.48177126
 53.80585983 52.44615282]
